"""empty message

Revision ID: 0ae95806a0fb
Revises: eb0492318c99
Create Date: 2020-07-25 17:08:50.491482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae95806a0fb'
down_revision = 'eb0492318c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_meals',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    op.drop_column('orders', 'meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('meals', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('orders_meals')
    # ### end Alembic commands ###
