"""empty message

Revision ID: 40a2c06195c2
Revises: fb54fb9f4c5b
Create Date: 2020-07-23 14:47:23.890517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a2c06195c2'
down_revision = 'fb54fb9f4c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'datetime')
    # ### end Alembic commands ###
