"""empty message

Revision ID: eb0492318c99
Revises: e7f72d20d6ed
Create Date: 2020-07-24 16:37:40.159240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0492318c99'
down_revision = 'e7f72d20d6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_meals',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name='orders_meals_meal_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='orders_meals_order_id_fkey')
    )
    # ### end Alembic commands ###
