"""empty message

Revision ID: fb54fb9f4c5b
Revises: 3e77e4c02787
Create Date: 2020-07-23 14:13:54.527932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb54fb9f4c5b'
down_revision = '3e77e4c02787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
